'''
Module containing dictionaries for solar orientation and aggregation methods.
'''

solar_dict={
    'Süd': 0,
    'Süd-Ost': -45,
    'Süd-West': 45,
    'Ost': -90,
    'West': 90,
    'Nord-Ost': -135,
    'Nord-West': 135,
    'Nord': 180
}

generator_agg_dict = {'bus': 'first',
            'control' : 'last', # as first might be Slack
            'type' : 'first',
            'p_nom' : 'sum',
            'p_nom_mod' : 'sum',
            'p_nom_extendable' : 'first',
            'p_nom_min' : 'sum', # only for capacity expansion
            'p_nom_max' : 'sum',
            'p_nom_set' : 'sum',
            'p_min_pu' : 'mean', # small error: normally we should use weighted mean here
            'p_max_pu' : 'mean', # same here
            'p_set' : 'sum',
            'e_sum_min' : 'sum',
            'e_sum_max' : 'sum',
            'q_set' : 'sum', # ?
            'sign' : 'first',
            'carrier': 'first',
            'marginal_cost' : 'mean',
            'marginal_cost_quadratic' : 'sum',
            'active' : 'first',
            'build_year' : 'mean',
            'lifetime' : 'mean',
            'capital_cost' : 'mean',
            'efficiency': 'mean',
            'committable' : 'first',
            'start_up_cost' : 'mean',
            'shut_down_cost' : 'mean',
            'stand_by_cost' : 'mean',
            'min_up_time' : 'mean',
            'min_down_time' : 'mean',
            'up_time_before' : 'mean',
            'down_time_before' : 'mean',
            'ramp_limit_up' : 'mean',
            'ramp_limit_down' : 'mean',
            'ramp_limit_start_up' : 'mean',
            'ramp_limit_shut_down' : 'mean',
            'weight' : 'mean',
            'p_nom_opt': 'sum',
            'weather_cell_id': 'first',
            'subtype': 'first',
            'source_id': 'first',
            'voltage_level': 'first',
            }

agg_dict={
    'Zensus_Holz_Holzpellets': 'sum',
    'Zensus_Kohle': 'sum',
    'Zensus_Geb_Fernwaerme': 'sum',
    'Zensus_Gas': 'sum',
    'Zensus_Geb_Holz_Holzpellets': 'sum',
    'Zensus_Geb_Kohle': 'sum',
    'Zensus_durchschnMieteQM': 'mean',
    'Zensus_30bis39': 'sum',
    'Zensus_40bis49': 'sum',
    'Zensus_Geb_FreiEFH': 'sum',
    'Zensus_Freist_ZFH': 'sum',
    'Zensus_EU27_Land': 'sum',
    'Zensus_1_Person': 'sum',
    'Zensus_2_Personen': 'sum',
    'Zensus_3_Personen': 'sum',
    'Zensus_4_Personen': 'sum',
    'Zensus_5_Personen': 'sum',
    'Zensus_6_Personen_und_mehr': 'sum',
    'Zensus_Ehep_Kinder_ab18': 'sum',
    'Zensus_NichtehelLG_mind_1Kind_unter18': 'sum',
    'Zensus_Vor1919': 'sum',
    'Zensus_a1970bis1979': 'sum',
    'Zensus_1_Wohnung': 'sum',
    'Zensus_2_Wohnungen': 'sum',
    'Zensus_3bis6_Wohnungen': 'sum',
    'Zensus_7bis12_Wohnungen': 'sum',
    'Zensus_13undmehr_Wohnungen': 'sum',
    }



agg_dict_all={
        'Zensus_Einwohner': 'sum',

    'Zensus_Fernheizung': 'sum',
    'Zensus_Etagenheizung': 'sum',
    'Zensus_Blockheizung': 'sum',
    'Zensus_Zentralheizung': 'sum',
    'Zensus_Einzel_Mehrraumoefen': 'sum',
    'Zensus_keine_Heizung': 'sum',

    'Zensus_Geb_Fernheizung': 'sum',
    'Zensus_Geb_Etagenheizung': 'sum',
    'Zensus_Geb_Blockheizung': 'sum',
    'Zensus_Geb_Zentralheizung': 'sum',
    'Zensus_Geb_Einzel_Mehrraumoefen': 'sum',
    'Zensus_Geb_keine_Heizung': 'sum',

    'Zensus_Gas': 'sum',
    'Zensus_Heizoel': 'sum',
    'Zensus_Holz_Holzpellets': 'sum',
    'Zensus_Biomasse_Biogas': 'sum',
    'Zensus_Solar_Geothermie_Waermepumpen': 'sum',
    'Zensus_Strom': 'sum',
    'Zensus_Kohle': 'sum',
    'Zensus_Fernwaerme': 'sum',
    'Zensus_kein_Energietraeger': 'sum',

    'Zensus_Geb_Gas': 'sum',
    'Zensus_Geb_Heizoel': 'sum',
    'Zensus_Geb_Holz_Holzpellets': 'sum',
    'Zensus_Geb_Biomasse_Biogas': 'sum',
    'Zensus_Geb_Solar_Geothermie_Waermepumpen': 'sum',
    'Zensus_Geb_Strom': 'sum',
    'Zensus_Geb_Kohle': 'sum',
    'Zensus_Geb_Fernwaerme': 'sum',
    'Zensus_Geb_kein_Energietraeger': 'sum',

    'Zensus_durchschnMieteQM': 'mean',
    'Zensus_AnzahlWohnungen': 'sum',
    'Zensus_Eigentuemerquote': 'mean',
    'Zensus_Leerstandsquote': 'mean',
    'Zensus_marktaktive_Leerstandsquote': 'mean',
    'Zensus_durchschnFlaechejeBew': 'mean',
    'Zensus_durchschnFlaechejeWohn': 'mean',

    'Zensus_unter30': 'sum',
    'Zensus_30bis39': 'sum',
    'Zensus_40bis49': 'sum',
    'Zensus_50bis59': 'sum',
    'Zensus_60bis69': 'sum',
    'Zensus_70bis79': 'sum',
    'Zensus_80bis89': 'sum',
    'Zensus_90bis99': 'sum',
    'Zensus_100bis109': 'sum',
    'Zensus_110bis119': 'sum',
    'Zensus_120bis129': 'sum',
    'Zensus_130bis139': 'sum',
    'Zensus_140bis149': 'sum',
    'Zensus_150bis159': 'sum',
    'Zensus_160bis169': 'sum',
    'Zensus_170bis179': 'sum',
    'Zensus_180undmehr': 'sum',

    'Zensus_FreiEFH': 'sum',
    'Zensus_EFH_DHH': 'sum',
    'Zensus_EFH_Reihenhaus': 'sum',
    'Zensus_Freist_ZFH': 'sum',
    'Zensus_ZFH_DHH': 'sum',
    'Zensus_ZFH_Reihenhaus': 'sum',
    'Zensus_MFH_3bis6Wohnungen': 'sum',
    'Zensus_MFH_7bis12Wohnungen': 'sum',
    'Zensus_MFH_13undmehrWohnungen': 'sum',
    'Zensus_AndererGebaeudetyp': 'sum',

    'Zensus_1Raum': 'sum',
    'Zensus_2Raeume': 'sum',
    'Zensus_3Raeume': 'sum',
    'Zensus_4Raeume': 'sum',
    'Zensus_5Raeume': 'sum',
    'Zensus_6Raeume': 'sum',
    'Zensus_7undmehrRaeume': 'sum',

    'Zensus_Deutschland': 'sum',
    'Zensus_Ausland_Sonstige': 'sum',
    'Zensus_EU27_Land': 'sum',
    'Zensus_Sonstiges_Europa': 'sum',
    'Zensus_Sonstige_Welt': 'sum',
    'Zensus_Sonstige': 'sum',

    'Zensus_Geb_Deutschland': 'sum',
    'Zensus_Geb_Ausland_Sonstige': 'sum',
    'Zensus_Geb_EU27_Land': 'sum',
    'Zensus_Geb_Sonstiges_Europa': 'sum',
    'Zensus_Geb_Sonstige_Welt': 'sum',
    'Zensus_Geb_Sonstige': 'sum',

    'Zensus_Unter10': 'sum',
    'Zensus_a10bis19': 'sum',
    'Zensus_a20bis29': 'sum',
    'Zensus_a30bis39': 'sum',
    'Zensus_a40bis49': 'sum',
    'Zensus_a50bis59': 'sum',
    'Zensus_a60bis69': 'sum',
    'Zensus_a70bis79': 'sum',
    'Zensus_a80undaelter': 'sum',


    'Zensus_Ledig': 'sum',
    'Zensus_Verheiratet': 'sum',
    'Zensus_Verwitwet': 'sum',
    'Zensus_Geschieden': 'sum',
    'Zensus_EingetrLebenspartnerschaft': 'sum',
    'Zensus_EingetrLebenspartVerstorben': 'sum',
    'Zensus_EingetrLebenspartAufgehoben': 'sum',
    'Zensus_OhneAngabe': 'sum',

    'Zensus_DurchschnHHGroesse': 'mean',

    'Zensus_1_Person': 'sum',
    'Zensus_2_Personen': 'sum',
    'Zensus_3_Personen': 'sum',
    'Zensus_4_Personen': 'sum',
    'Zensus_5_Personen': 'sum',
    'Zensus_6_Personen_und_mehr': 'sum',

    'Zensus_Ehep_ohneKind': 'sum',
    'Zensus_Ehep_mind_1Kind_unter18': 'sum',
    'Zensus_Ehep_Kinder_ab18': 'sum',
    'Zensus_EingetrLP_ohneKind': 'sum',
    'Zensus_EingetrLP_mind_1Kind_unter18': 'sum',
    'Zensus_EingetrLP_Kinder_ab18': 'sum',
    'Zensus_NichtehelLG_ohneKind': 'sum',
    'Zensus_NichtehelLG_mind_1Kind_unter18': 'sum',
    'Zensus_NichtehelLG_Kinder_ab18': 'sum',
    'Zensus_Vater_mind_1Kind_unter18': 'sum',
    'Zensus_Vater_Kinder_ab18': 'sum',
    'Zensus_Mutter_mind_1Kind_unter18': 'sum',
    'Zensus_Mutter_Kinder_ab18': 'sum',

    'Zensus_a2Personen': 'sum',
    'Zensus_a3Personen': 'sum',
    'Zensus_a4Personen': 'sum',
    'Zensus_a5Personen': 'sum',
    'Zensus_a6Pers_und_mehr': 'sum',

    'Zensus_EinpersHH_SingleHH': 'sum',
    'Zensus_Ehepaare': 'sum',
    'Zensus_EingetrLebensp': 'sum',
    'Zensus_NichtehelLebensg': 'sum',
    'Zensus_AlleinerzMuetter': 'sum',
    'Zensus_AlleinerzVaeter': 'sum',
    'Zensus_MehrpersHHohneKernfam': 'sum',

    'Zensus_Fam_EinpersHH_SingleHH': 'sum',
    'Zensus_Fam_Paare_ohneKind': 'sum',
    'Zensus_Fam_Paare_mitKind': 'sum',
    'Zensus_Fam_Alleinerziehende': 'sum',
    'Zensus_Fam_MehrpersHHohneKernfam': 'sum',

    'Zensus_HH_nurSenioren': 'sum',
    'Zensus_HH_mitSenioren': 'sum',
    'Zensus_HH_ohneSenioren': 'sum',

    'Zensus_Vor1919': 'sum',
    'Zensus_a1919bis1949': 'sum',
    'Zensus_a1950bis1959': 'sum',
    'Zensus_a1960bis1969': 'sum',
    'Zensus_a1970bis1979': 'sum',
    'Zensus_a1980bis1989': 'sum',
    'Zensus_a1990bis1999': 'sum',
    'Zensus_a2000bis2009': 'sum',
    'Zensus_a2010bis2015': 'sum',
    'Zensus_a2016undspaeter': 'sum',

    'Zensus_1_Wohnung': 'sum',
    'Zensus_2_Wohnungen': 'sum',
    'Zensus_3bis6_Wohnungen': 'sum',
    'Zensus_7bis12_Wohnungen': 'sum',
    'Zensus_13undmehr_Wohnungen': 'sum',

    'Zensus_Geb_FreiEFH': 'sum',
    'Zensus_Geb_EFH_DHH': 'sum',
    'Zensus_Geb_EFH_Reihenhaus': 'sum',
    'Zensus_Geb_Freist_ZFH': 'sum',
    'Zensus_Geb_ZFH_DHH': 'sum',
    'Zensus_Geb_ZFH_Reihenhaus': 'sum',
    'Zensus_Geb_MFH_3bis6Wohnungen': 'sum',
    'Zensus_Geb_MFH_7bis12Wohnungen': 'sum',
    'Zensus_Geb_MFH_13undmehrWohnungen': 'sum',
    'Zensus_Geb_AndererGebaeudetyp': 'sum'
    }